import { PERMISSIONS } from "./constants.js";

export const roleMatrix = {
  employee: [
    PERMISSIONS.INITIATIVE_CREATE,
    PERMISSIONS.GOVERNANCE_APPROVE
  ],
  lead: [
    PERMISSIONS.INITIATIVE_CREATE,
    PERMISSIONS.INITIATIVE_STATUS_UPDATE,
    PERMISSIONS.GOVERNANCE_APPROVE
  ],
  judge: [
    PERMISSIONS.INITIATIVE_READ_ALL,
    PERMISSIONS.INITIATIVE_EVALUATE,
    PERMISSIONS.AUDIT_READ
  ],
  supervisor: [
    PERMISSIONS.INITIATIVE_READ_ALL,
    PERMISSIONS.INITIATIVE_STATUS_UPDATE,
    PERMISSIONS.INITIATIVE_REJECT,
    PERMISSIONS.GOVERNANCE_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.JUDGING_LOCK
  ],
  executive: ["*"]
};
