export const METHOD_TOOLKIT = [
  {
    id: 'tool-scamper',
    title: 'SCAMPER لتوليد الأفكار',
    stage: 'Idea',
    source: '3.pdf',
    purpose: 'توسيع بدائل الحل وتوليد أفكار جديدة بشكل منظم.',
  },
  {
    id: 'tool-decision-matrix',
    title: 'مصفوفة القرار',
    stage: 'Evaluation',
    source: '5.pdf',
    purpose: 'مفاضلة الأفكار حسب الأهمية والتكلفة والملاءمة.',
  },
  {
    id: 'tool-storyboard',
    title: 'Storyboard (لوحة القصة)',
    stage: 'Prototype',
    source: '10.pdf',
    purpose: 'تصميم سيناريو تجربة المستخدم من البداية للنهاية.',
  },
  {
    id: 'tool-mvp',
    title: 'Minimum Viable Product (MVP)',
    stage: 'Prototype',
    source: '11.pdf',
    purpose: 'إطلاق نسخة أولية منخفضة المخاطر للتحقق من الفرضيات.',
  },
  {
    id: 'tool-test-learn',
    title: 'بطاقة الاختبار والتعلم',
    stage: 'Simulation',
    source: '12.pdf',
    purpose: 'قياس الفرضيات وتحديد قرار الاستمرار أو التعديل.',
  },
  {
    id: 'tool-cashflow',
    title: 'قائمة التدفق النقدي',
    stage: 'Simulation',
    source: '17.pdf',
    purpose: 'متابعة السيولة وقدرة المشروع على الاستدامة المالية.',
  },
  {
    id: 'tool-balance-sheet',
    title: 'قائمة المركز المالي',
    stage: 'Simulation',
    source: '18.pdf',
    purpose: 'تقدير الأصول والالتزامات ووضوح الوضع المالي للمبادرة.',
  },
  {
    id: 'tool-financial-ratios',
    title: 'ROI / Break-even / Payback',
    stage: 'Simulation',
    source: '20.pdf',
    purpose: 'قياس جدوى التنفيذ والعائد المتوقع وفترة الاسترداد.',
  },
  {
    id: 'tool-marketing-plan',
    title: 'الخطة التسويقية',
    stage: 'Marketplace',
    source: '21.pdf',
    purpose: 'تحديد الشرائح والقنوات ومؤشرات النجاح للوصول للتبني.',
  },
  {
    id: 'tool-value-proposition',
    title: 'Value Proposition Designer',
    stage: 'Evaluation',
    source: '22.pdf',
    purpose: 'مواءمة المشكلة مع القيمة الفريدة المقدمة للمستفيد.',
  },
  {
    id: 'tool-pitch-evaluation',
    title: 'تقييم العرض التجريبي',
    stage: 'Adoption',
    source: '23.pdf',
    purpose: 'رفع جاهزية الفريق قبل العرض النهائي واتخاذ القرار.',
  },
  {
    id: 'tool-ui-reference',
    title: 'Food Delivery App Guide',
    stage: 'Prototype',
    source: '5fa2b34722e13a2b6c07ee25_Food Delivery App _ Guide.pdf',
    purpose: 'مرجع UX/UI لبناء تدفقات رقمية واضحة وقابلة للتبني.',
  },
]
