import { PERMISSIONS } from "../../core/constants.js";

export function getRoleMatrixV2() {
  return {
    innovator: [
      PERMISSIONS.PAGE_INITIATIVES_VIEW,
      PERMISSIONS.PAGE_PROTOTYPES_VIEW,
      PERMISSIONS.PAGE_GOVERNANCE_VIEW,
      PERMISSIONS.INITIATIVE_CREATE,
      PERMISSIONS.PROTOTYPE_SUPPORT_REQUEST,
      PERMISSIONS.GOVERNANCE_PLEDGE_SIGN,
    ],
    evaluator: [
      PERMISSIONS.PAGE_ADMIN_JUDGING_VIEW,
      PERMISSIONS.INITIATIVE_EVALUATE,
      PERMISSIONS.JUDGING_LOCK,
      PERMISSIONS.AUDIT_READ,
    ],
    manager: [
      PERMISSIONS.PAGE_ADMIN_OVERVIEW_VIEW,
      PERMISSIONS.PAGE_ADMIN_ACCESS_VIEW,
      PERMISSIONS.PAGE_ADMIN_INITIATIVES_VIEW,
      PERMISSIONS.PAGE_ADMIN_AUDIT_VIEW,
      PERMISSIONS.INITIATIVE_APPROVE,
      PERMISSIONS.GOVERNANCE_POLICY_MANAGE,
      PERMISSIONS.ADMIN_ACCESS,
    ],
    committee: [
      PERMISSIONS.PAGE_ADMIN_OVERVIEW_VIEW,
      PERMISSIONS.INITIATIVE_APPROVE,
      PERMISSIONS.REWARD_MANAGE,
      PERMISSIONS.AUDIT_READ,
    ],
  };
}
